version: '3'

services:
  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=reddit
    ports:
      - '27017-27019:27017-27019'

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
